language: ruby
services:
  - docker
install:
  - docker-compose up -d
  - sleep 10
before_script:
  - gem install mechanize
script:
  - docker-compose exec wp cli --info
after_script:
  - ruby tests/test.rb
  - docker-compose stop
  - docker-compose rm -f